#!/usr/bin/env bash

# ============= #
# CONFIGURATION #
# ============= #

NEW_USER="harmon"
REQUIRED_GROUPS=("sudo")
TERMIUS_PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAe1MIwDQGa49p+l6fIAPB3/1zgfzApIJfrgiV0tcfnD Generated By Termius"
NET_QDISC="fq"
TCP_CONG="bbr"
SWAPPINESS="60"
SWAP_SIZE="4G"
SWAP_PATH="/swapfile"

export DEBIAN_FRONTEND=noninteractive

# Color Output Helpers
info() { echo -e "\e[32m[INFO] $*\e[0m"; }
warn() { echo -e "\e[33m[WARN] $*\e[0m"; }
error() {
  echo -e "\e[31m[ERROR] $*\e[0m"
  exit 1
}

# ================================== #
# 1. USER & PRIVILEGE INITIALIZATION #
# ================================== #

setup_user() {
  if id "${NEW_USER}" &>/dev/null; then
    info "user ${NEW_USER} already exists, skipping creation."
  else
    useradd -m -s /bin/bash "${NEW_USER}" || error "failed to create user ${NEW_USER}"
    info "successfully created user ${NEW_USER}"
  fi

  for g in "${REQUIRED_GROUPS[@]}"; do
    if getent group "$g" &>/dev/null; then
      if ! id -nG "${NEW_USER}" | grep -qw "$g"; then
        usermod -aG "$g" "${NEW_USER}"
        info "add user ${NEW_USER} to group $g"
      fi
    fi
  done

  local sudo_conf_g="/etc/sudoers"
  local sudo_conf_tmp="/tmp/sudoers"
  local src_rule_E="^%sudo[[:space:]]ALL=\(ALL:ALL\)[[:space:]]ALL"
  local dest_rule_F="%sudo ALL=(ALL:ALL) NOPASSWD: ALL"
  if [[ -s "${sudo_conf_g}" ]]; then
    if grep -qE "${src_rule_E}" "${sudo_conf_g}"; then
      sed -E "s/${src_rule_E}/${dest_rule_F}/" "${sudo_conf_g}" >"${sudo_conf_tmp}"
      if visudo -cf "${sudo_conf_tmp}" >/dev/null; then
        cat "${sudo_conf_tmp}" >"${sudo_conf_g}"
        chmod 440 "${sudo_conf_g}"
        visudo -cf "${sudo_conf_g}" >/dev/null || error "critical wrong with ${sudo_conf_g}, os may destroyed"
      else
        warn "syntax wrong with ${sudo_conf_tmp}, skip overwrite"
      fi
    fi
  else
    warn "${sudo_conf_g} not found!"
  fi

  local sudo_conf_u="/etc/sudoers.d/${NEW_USER}"
  if [[ ! -s "${sudo_conf_u}" ]]; then
    echo "${NEW_USER} ALL=(ALL : ALL) NOPASSWD: ALL" >>"${sudo_conf_u}"
    chmod 440 "${sudo_conf_u}"
    visudo -cf "${sudo_conf_u}" >/dev/null || error "sudoers.d syntax check failed"
    info "sudo passwordless access configured for ${NEW_USER}"
  else
    warn "${sudo_conf_u} already exists."
  fi

  local pam_auth_conf="/usr/share/pam-configs/nopasswd"
  if [[ ! -f "${pam_auth_conf}" ]]; then
    cat >"${pam_auth_conf}" <<EOF
Name: Global passwordless for specified users
Default: yes
Priority: 1024
Auth-Type: Primary
Auth:
[success=done default=ignore] pam_succeed_if.so ingroup sudo
EOF
    info "set sudo group passwordless"
  else
    warn "${pam_auth_conf} already exists, check manually!"
  fi

  local pam_rule_uF="[success=done default=ignore] pam_succeed_if.so user = ${NEW_USER}"
  if ! grep -qF "${pam_rule_uF}" "${pam_auth_conf}"; then
    echo "${pam_rule_uF}" >>"${pam_auth_conf}"
    info "set user ${NEW_USER} passwordless"
  else
    info "user ${NEW_USER} already passwordless"
  fi

  if pam-auth-update --package; then
    info "pam-auth update successfully"
  else
    warn "pam-auth update fail, check manually"
  fi
}

# =================================== #
# 2. SSH HARDENING & PUBKEY INJECTION #
# =================================== #

setup_ssh() {
  local home_dir
  home_dir=$(eval "echo ~${NEW_USER}")
  local ssh_dir="${home_dir}/.ssh"
  local keys_file="${ssh_dir}/authorized_keys"
  mkdir -p "${ssh_dir}"
  if [[ -f "${keys_file}" ]]; then
    if ! grep -qF "${TERMIUS_PUBKEY}" "${keys_file}"; then
      echo "${TERMIUS_PUBKEY}" >>"${keys_file}"
      info "Public key injected into ${NEW_USER}'s authorized_keys"
    fi
  else
    echo "${TERMIUS_PUBKEY}" >>"${keys_file}"
    info "Public key injected into ${NEW_USER}'s authorized_keys"
  fi
  chown -R "${NEW_USER}:${NEW_USER}" "${ssh_dir}"
  chown -R "${NEW_USER}:${NEW_USER}" "${keys_file}"
  chmod 700 "${ssh_dir}"
  chmod 600 "${keys_file}"

  local sshd_conf_custom="/etc/ssh/sshd_config.d/${NEW_USER}.conf"
  if [[ ! -s "${sshd_conf_custom}" ]]; then
    tee "${sshd_conf_custom}" <<EOF >/dev/null
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
PermitRootLogin no
ClientAliveInterval 60
UsePAM yes
EOF
    if sshd -t; then
      if systemctl is-active --quiet ssh.socket; then
        if systemctl daemon-reload && systemctl restart ssh.socket; then
          info "SSH hardening applied successfully (socket)"
        fi
      else
        systemctl restart ssh && info "SSH hardening applied successfully"
      fi
    else
      rm "${sshd_conf_custom}"
      error "SSHD configuration syntax error, rolled back changes"
    fi
  else
    warn "SSH custom configuration already exists, skipping."
  fi
}

# ============================= #
# 3. KERNEL TUNING (BBR & SWAP) #
# ============================= #

setup_sysctl() {
  local need_reload=false
  local conf_file="/etc/sysctl.conf"
  local net_qdisc="${NET_QDISC}"
  local tcp_cong="${TCP_CONG}"
  local swappiness="${SWAPPINESS}"
  declare -A params=(
    ["net.core.default_qdisc"]="${net_qdisc}"
    ["net.ipv4.tcp_congestion_control"]="${tcp_cong}"
    ["vm.swappiness"]="${swappiness}"
  )
  for key in "${!params[@]}"; do
    if [[ $(sysctl -n "${key}") != "${params["${key}"]}" ]]; then
      sed -i "/^[[:space:]]*${key}/d" "${conf_file}"
      echo "${key} = ${params["${key}"]}" >>"${conf_file}"
      need_reload=true
    fi
  done
  if [[ ${need_reload} == true ]]; then
    sysctl -p >/dev/null
    info "Kernel parameters optimized (BBR & Swappiness)"
  fi
}

setup_swap() {
  local swap_file="${SWAP_PATH}"
  if swapon --show=NAME --noheadings | grep -qxF "${swap_file}"; then
    warn "Swap is already active, skipping."
  else
    local free_kb
    free_kb=$(df --output=avail / | tail -n1)
    local swap_size="${SWAP_SIZE}"
    if [[ "${free_kb}" -lt "$((${swap_size%G} * 1024 * 1024 + 5 * 1024 * 1024))" ]]; then
      warn "Insufficient disk space, skipping swap creation."
      return 1
    fi
    if [[ -f "${swap_file}" ]]; then
      warn "${swap_file} already exists, skip."
    else
      info "Creating ${SWAP_SIZE} swap file. This may take a few seconds..."
      fallocate -l "${swap_size}" "${swap_file}"
      chmod 600 "${swap_file}"
      mkswap "${swap_file}" >/dev/null
      if ! swapon "${swap_file}"; then
        warn "fallocate failed to create a valid swap. Retrying with dd..."
        rm -rf "${swap_file}"
        dd if=/dev/zero of="${swap_file}" bs="1G" count="${swap_size%G}"
        chmod 600 "${swap_file}"
        mkswap "${swap_file}"
        swapon "${swap_file}" || {
          warn "dd failed to create a valid swap."
          return 1
        }
      fi
      if ! grep -q "${swap_file}" "/etc/fstab"; then
        echo "${swap_file} none swap sw 0 0" >>"/etc/fstab"
        info "Swap file created and activated successfully."
      fi
    fi
  fi
}

# ================= #
# MAIN CONTROL FLOW #
# ================= #

main() {
  # Ensure script is running with root privileges
  if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root. Try: sudo bash $0"
  fi

  info "Starting system initialization..."
  setup_user
  setup_ssh
  setup_sysctl
  setup_swap
  info "System initialization completed successfully!"

  info "Please test the connection with user: '${NEW_USER}' in a new terminal."
}

main "$@"
