#!/usr/bin/env bash

# ============= #
# CONFIGURATION #
# ============= #

NEW_USER="harmon"
REQUIRED_GROUPS=("sudo")
TERMIUS_PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAe1MIwDQGa49p+l6fIAPB3/1zgfzApIJfrgiV0tcfnD Generated By Termius"
NET_QDISC="fq"
TCP_CONG="bbr"
SWAPPINESS="60"
SWAP_SIZE="4G"
SWAP_PATH="/swapfile"

export DEBIAN_FRONTEND=noninteractive

# Color Output Helpers
info() { echo -e "\e[32m[INFO] $*\e[0m"; }
warn() { echo -e "\e[33m[WARN] $*\e[0m"; }
error() {
  echo -e "\e[31m[ERROR] $*\e[0m"
  exit 1
}

# ================================== #
# 1. USER & PRIVILEGE INITIALIZATION #
# ================================== #

setup_user() {
  if id "${NEW_USER}" &>/dev/null; then
    info "user ${NEW_USER} already exists, skipping creation."
  else
    useradd -m -s /bin/bash "${NEW_USER}" || error "failed to create user ${NEW_USER}"
    info "successfully created user ${NEW_USER}"
  fi

  for g in "${REQUIRED_GROUPS[@]}"; do
    if getent group "$g" &>/dev/null; then
      if ! id -nG "${NEW_USER}" | grep -qw "$g"; then
        usermod -aG "$g" "${NEW_USER}"
        info "add user ${NEW_USER} to group $g"
      fi
    fi
  done

  local sudo_conf="/etc/sudoers.d/${NEW_USER}"
  if [[ ! -s "${sudo_conf}" ]]; then
    echo "${NEW_USER} ALL=(ALL : ALL) NOPASSWD: ALL" | tee "${sudo_conf}" >/dev/null
    chmod 440 "${sudo_conf}"
    visudo -cf "${sudo_conf}" >/dev/null || error "sudoers syntax check failed"
    info "sudo passwordless access configured for ${NEW_USER}"
  else
    warn "${sudo_conf} already exists."
  fi
}
# if sudo visudo -cf "${sudo_conf}"; then
#   sudo_rules=$(sudo -nl)
#   if echo "${sudo_rules}" | grep -q "NOPASSWD: ALL"; then
#     echo "all sudo commands set no passward"
#   elif echo "${sudo_rules}" | grep -q "NOPASSWD"; then
#     echo "part of sudo commands set no passward"
#   else
#     echo "sudo commands set passward"
#   fi
# else
#   echo "Attention! Some problem with file ${sudo_conf}. Please check it!"
# fi

# =================================== #
# 2. SSH HARDENING & PUBKEY INJECTION #
# =================================== #

setup_ssh() {
  local home_dir
  home_dir=$(eval "echo ~${NEW_USER}")
  local ssh_dir="${home_dir}/.ssh"
  local keys_file="${ssh_dir}/authorized_keys"
  mkdir -p "${ssh_dir}"
  if [[ -f "${keys_file}" ]]; then
    if ! grep -qF "${TERMIUS_PUBKEY}" "${keys_file}"; then
      echo "${TERMIUS_PUBKEY}" >>"${keys_file}"
      info "Public key injected into ${NEW_USER}'s authorized_keys"
    fi
  else
    echo "${TERMIUS_PUBKEY}" >>"${keys_file}"
    info "Public key injected into ${NEW_USER}'s authorized_keys"
  fi
  chown -R "${NEW_USER}:${NEW_USER}" "${ssh_dir}"
  chown -R "${NEW_USER}:${NEW_USER}" "${keys_file}"
  chmod 700 "${ssh_dir}"
  chmod 600 "${keys_file}"

  local sshd_conf_custom="/etc/ssh/sshd_config.d/${NEW_USER}.conf"
  if [[ ! -s "${sshd_conf_custom}" ]]; then
    tee "${sshd_conf_custom}" <<EOF >/dev/null
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
PermitRootLogin no
ClientAliveInterval 60
UsePAM yes
EOF
    if sshd -t; then
      if systemctl is-active --quiet ssh.socket; then
        if systemctl daemon-reload && systemctl restart ssh.socket; then
          info "SSH hardening applied successfully (socket)"
        fi
      else
        systemctl restart ssh && info "SSH hardening applied successfully"
      fi
    else
      rm "${sshd_conf_custom}"
      error "SSHD configuration syntax error, rolled back changes"
    fi
  else
    warn "SSH custom configuration already exists, skipping."
  fi
}

# set_sysctl() {
#   local key="$1"
#   local value="$2"
#   local conf_file="/etc/sysctl.conf"
#
#   local current_value
#   if ! current_value="$(sysctl -n "${key}" 2>&1)"; then
#     echo "error: ${current_value}"
#     return 1
#   fi
#   if [[ "${current_value}" == "${value}" ]]; then
#     echo "current value of key is right. do nothing"
#     return 0
#   else
#     sudo sed "s/${key}.*=.*${current_value}//" "${conf_file}"
#     echo "${key} = ${value}" | sudo tee -a "${conf_file}"
#     echo "write to ${conf_file}"
#   fi
#   current_value="$(sysctl -n "${key}")"
#   if [[ "${current_value}" == "${value}" ]]; then
#     if sudo sysctl -p; then
#       echo "error: set failure"
#       return 1
#     fi
#     echo "set successfully"
#     return 0
#   else
#     echo "unexpected failure"
#     return 1
#   fi
# }

# ============================= #
# 3. KERNEL TUNING (BBR & SWAP) #
# ============================= #

setup_sysctl() {
  local need_reload=false
  local conf_file="/etc/sysctl.conf"
  local net_qdisc="${NET_QDISC}"
  local tcp_cong="${TCP_CONG}"
  local swappiness="${SWAPPINESS}"
  declare -A params=(
    ["net.core.default_qdisc"]="${net_qdisc}"
    ["net.ipv4.tcp_congestion_control"]="${tcp_cong}"
    ["vm.swappiness"]="${swappiness}"
  )
  for key in "${!params[@]}"; do
    if [[ $(sysctl -n "${key}") != "${params["${key}"]}" ]]; then
      sed -i "/^[[:space:]]*${key}/d" "${conf_file}"
      echo "${key} = ${params["${key}"]}" >>"${conf_file}"
      need_reload=true
    fi
  done
  if [[ ${need_reload} == true ]]; then
    sysctl -p >/dev/null
    info "Kernel parameters optimized (BBR & Swappiness)"
  fi
}

# if [[ $(sysctl -n net.core.default_qdisc) != "fq" ]]; then
#   sudo tee -a "/etc/sysctl.conf" <<EOF
# net.core.default_qdisc = fq
# EOF
#   sudo sysctl -p
#   echo "set net.core.default_qdisc = fq"
# fi
#
# if [[ $(sysctl -n net.ipv4.tcp_congestion_control) != "bbr" ]]; then
#   sudo tee -a "/etc/sysctl.conf" <<EOF
# net.ipv4.tcp_congestion_control = bbr
# EOF
#   sudo sysctl -p
#   echo "set net.ipv4.tcp_congestion_control = bbr"
# fi

setup_swap() {
  local swap_file="${SWAP_PATH}"
  if swapon --show=NAME --noheadings | grep -qxF "${swap_file}"; then
    warn "Swap is already active, skipping."
  else
    local free_kb
    free_kb=$(df --output=avail / | tail -n1)
    local swap_size="${SWAP_SIZE}"
    if [[ "${free_kb}" -lt "$((${swap_size%G} * 1024 * 1024 + 5 * 1024 * 1024))" ]]; then
      warn "Insufficient disk space, skipping swap creation."
      return 1
    fi
    if [[ -f "${swap_file}" ]]; then
      warn "${swap_file} already exists, skip."
    else
      info "Creating ${SWAP_SIZE} swap file. This may take a few seconds..."
      fallocate -l "${swap_size}" "${swap_file}"
      chmod 600 "${swap_file}"
      mkswap "${swap_file}" >/dev/null
      if ! swapon "${swap_file}"; then
        warn "fallocate failed to create a valid swap. Retrying with dd..."
        rm -rf "${swap_file}"
        dd if=/dev/zero of="${swap_file}" bs="1G" count="${swap_size%G}"
        chmod 600 "${swap_file}"
        mkswap "${swap_file}"
        swapon "${swap_file}" || {
          warn "dd failed to create a valid swap."
          return 1
        }
      fi
      if ! grep -q "${swap_file}" "/etc/fstab"; then
        echo "${swap_file} none swap sw 0 0" >>"/etc/fstab"
        info "Swap file created and activated successfully."
      fi
    fi
  fi
}

# if [[ -f "${SWAP_PATH}" ]]; then
#   echo "swapfile exists"
# else
#   sudo fallocate -l "${SWAP_SIZE}" "${SWAP_PATH}"
#   sudo chmod 600 "${SWAP_PATH}"
#   sudo mkswap "${SWAP_PATH}"
#   sudo swapon "${SWAP_PATH}"
#   if ! grep -q "${SWAP_PATH}" /etc/fstab; then
#     echo "${SWAP_PATH} none swap sw 0 0" | sudo tee -a /etc/fstab
#   fi
#   echo "swap creates successfully"
# fi
#
# if [[ "$(sysctl -n vm.swappiness)" != 60 ]]; then
#   echo "vm.swappiness = 60" | sudo tee -a "/etc/sysctl.conf"
#   sudo sysctl -p
# fi

# ================= #
# MAIN CONTROL FLOW #
# ================= #

main() {
  # Ensure script is running with root privileges
  if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root. Try: sudo bash $0"
  fi

  info "Starting system initialization..."

  setup_user
  setup_ssh
  setup_sysctl
  setup_swap

  apt-get update -q >/dev/null && apt-get install build-essential procps curl file git -q -y >/dev/null

  info "System initialization completed successfully!"
  info "Please test the connection with user: '${NEW_USER}' in a new terminal."
}

main "$@"
