# remap prefix to Control + a
set -g prefix C-a
unbind C-b
bind a send-prefix

# force a reload of the config file
unbind r
bind r source-file ~/.tmux.conf

# quick pane cycling
unbind C-a
bind C-a select-pane -t :.+

# Use Vim shortcuts
setw -g mode-keys vi

