# remap prefix to Control + a
set -g prefix C-a
unbind C-b
bind a send-prefix

# force a reload of the config file
unbind r
bind r source-file ~/.tmux.conf

# quick pane cycling
unbind C-a
bind C-a select-pane -t :.+

# Use Vim shortcuts
setw -g mode-keys vi

set -g mouse on

set-option -g escape-time 0

set-option -g focus-events on

set-option -a terminal-features 'xterm-256color:RGB'

# YankBufferPost
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "cat > ~/yank.buf && tmux display-message \"Copy Success and write to ~/yank.buf\""
